- name: ping the server
  hosts: frontend # target server
  tasks: #tasks == module == collection
  - name: ping the server
    ping: #ansible.builtin.ping #module

#how to run
# $ansible-playbook -i inventory.ini01-playbook.yaml
# anasible modules
