- name: demo on var files
  hosts: local
  connection: local
  vars_files:
  - course.yaml
  tasks:
  - name: print varaible information
    debug:
      msg: "hi, I am learning {{ COURSE }} with {{ TRAINER }}, Duration is {{ DURATION }}"

