- name: demo on inventory files
  hosts: frontend
  #connection: local
  tasks:
  - name: print information
    debug:
      msg: "the course name is {{ COURSE }} and trainer is {{ TRAINER }} and duration is {{ DURATION }}, common_key is {{common_key}}"