- name: checking varables prefernce
  hosts: frontend
  vars:
    full_name: "priya from y"
  vars_files:
  - course.yaml
  vars_prompt:
  - name" full_name
    prompt: "enter your full name"
    private: false
  tasks:
  - name: print vars prefernces
    vars:
      full_name: "priya from task level"
    debug:
      msg: "HI {full_name}}"
  