- name: datatype
  hosts: local
  connection: local
  vars:
    course: "DevSecOps" #string
    duration_in_hrs: 150 
    is_live_sessions: true
    topics: #list
    - linux
    - shell
    - ansible
    more_deatils: #map
      trainer: "priya"
      course_content: "good"
      rating: 4.5
  tasks:
  - name: print information
    debug:
      msg:
        name: {{course}}
        duration: {{duration_in_hrs}}
        is_live_sessions: {{is_live_sessions}}
        topics: {{topics}}
        more_deatils: {{more_deatils}}