[frontend]
172.31.26.161 COURSE="Ansible node1" #individual host varibles
172.31.31.148 COURSE="Ansible node2"

;group of groups
[roboshp:children]
frontend
  

[local]
localhost

;local group vars
[local:vars]
COURSE="Ansible"
TRAINER="XX"
DURATION="103HRS"

[frontend:vars]
COURSE="Ansible"
TRAINER="XX"
DURATION="103HRS"